spring.application.name=recomendacionApp

# Conexion a MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/FilmFlux?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# TMDb API (Informacion de Peliculas o series)
tmdb.base-url=https://api.themoviedb.org/3
# Usa el "API Read Access Token" (el más largo)
tmdb.api-key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2ODNlMzlmYTdiMTIwY2Y2YTMxNGMxZmY4M2ZhOTNlZSIsIm5iZiI6MTc3NzkwMDk3OC41MzQwMDAysLCJzdWIiOiI2OWY4OWRiMmU0ZTJmMWRmZmEzMjcwNTAiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.ScC6ArNaiTRN7ujb9-FSU975gf9d_wkJuZB2pEa-W3s

# Spring Security - JWT
# IMPORTANTE: cambia este valor en produccion por uno aleatorio largo (min 32 caracteres)
jwt.secret=bibliotecaduoc-clave-secreta-jwt-2026-cambiar-en-produccion